export const STAGES = [
	{
		id: 0,
		name: "衛教影片",
		badge: "開場介紹",
		hint: "請先觀看完整衛教影片，了解吸入劑正確使用方式",
		icon: "🎬",
		videoURL:
			"https://www.youtube.com/embed/2DYT6jev8a4?rel=0&modestbranding=1",
		modelURL: null,
		passThreshold: 0,
		passSeconds: 0,
		manualPass: true,
		manualBtnText: "✅ 影片看完，開始挑戰！",
		badgeClass: "bg-gradient-to-br from-[#ff9a56] to-[#ff6b6b] text-black",
		titleClass: "text-[#ff9a56]",
		failHint: "",
		isIntro: true,
	},
	{
		id: 1,
		name: "振搖",
		badge: "第一關",
		// 「將吸入器上下搖動 4-5 次，使藥物充分混合」— 台灣胸腔暨重症加護醫學會, p.5。
		// 臨床標準是次數，不是秒數；偵測邏輯改為計數（見 steps/step1-shake.js）。
		hint: "請上下搖動吸入器 4-5 次，讓藥物充分混合",
		icon: "💊",
		stepEmoji: "💊",
		stepSub: "讓藥物充分混合，每次使用前都要搖",
		videoURL:
			"https://www.youtube.com/embed/itUWRBAkbR4?rel=0&modestbranding=1",
		modelURL: "https://teachablemachine.withgoogle.com/models/4s-Cq3RqD/",
		modelType: "image",
		passClass: "V振搖 正確",
		passThreshold: 0.85,
		passSeconds: 3,
		manualPass: false,
		showPharmacist: true,
		badgeClass: "bg-gradient-to-br from-[#ff9a56] to-[#ff6b6b] text-black",
		titleClass: "text-[#ff9a56]",
		failHint: "請持續搖勻吸入器，動作要明顯（需達 85%）",
		specialMode: "shake",
	},
	{
		id: 2,
		name: "吐氣",
		badge: "第二關",
		hint: "請慢慢吐氣至肺部排空，不要對著吸嘴吐氣",
		icon: "💨",
		stepEmoji: "💨",
		stepInstruction: "緩慢吐氣，直到肺部排空",
		stepSub: "⚠ 不要對著吸嘴吐氣，吐完才含入吸嘴",
		videoURL:
			"https://www.youtube.com/embed/lS0ppt5Aic0?rel=0&modestbranding=1",
		modelURL: "https://teachablemachine.withgoogle.com/models/EY9yUdpzU/",
		passClass: "吐氣",
		passThreshold: 0.85,
		passSeconds: 3,
		manualPass: false,
		showPharmacist: true,
		badgeClass: "bg-gradient-to-br from-[#a18cd1] to-[#fbc2eb] text-black",
		titleClass: "text-[#d4aaff]",
		failHint: "請重新吐氣，確認動作清楚",
	},
	{
		id: 3,
		name: "壓吸＋憋氣",
		badge: "第三關",
		hint: "將吸嘴放入口中，按壓同時深長吸氣，吸入後憋氣 5 秒",
		icon: "🫁",
		stepEmoji: "🫁",
		stepInstruction: "含住吸嘴 → 按壓 + 深吸氣 → 憋氣 5 秒",
		stepSub: "按壓與吸氣動作要同步，吸入後憋住不要馬上吐",
		videoURL:
			"https://www.youtube.com/embed/uH9Rw71MNvc?rel=0&modestbranding=1",
		modelURL: "https://teachablemachine.withgoogle.com/models/kOX75yZD8_/",
		passThreshold: 0.75,
		passClass: "吸壓_正確",
		passSeconds: 3,
		// 閉氣 5-10 秒（台灣胸腔暨重症加護醫學會, 肺阻塞的吸入性裝置衛教, p.5）。
		// 原本硬編碼為 3 秒，低於臨床下限。
		holdSeconds: 5,
		// 成人吸氣 4-5 秒且不可中斷（同上）。尚未實作檢查。
		inhaleSeconds: 4,
		manualPass: false,
		showPharmacist: true,
		badgeClass: "bg-gradient-to-br from-[#4facfe] to-[#00f2fe] text-black",
		titleClass: "text-[#4facfe]",
		failHint: "請再操作一次～加油！",
		specialMode: "holdBreath",
	},
	{
		id: 4,
		name: "漱口",
		badge: "第四關",
		hint: "吸藥後請以清水漱口並吐掉，保護口腔健康",
		icon: "💧",
		stepEmoji: "💧",
		stepInstruction: "含水漱口，再把水吐掉",
		stepSub: "去除口腔殘留藥物，預防念珠菌感染",
		videoURL:
			"https://www.youtube.com/embed/bhQ2fYn7GVo?rel=0&modestbranding=1",
		modelURL: "https://teachablemachine.withgoogle.com/models/ERFneU6fl/",
		passClass: "漱口_正確",
		passThreshold: 0.85,
		passSeconds: 3,
		manualPass: false,
		showPharmacist: true,
		badgeClass: "bg-gradient-to-br from-[#43e97b] to-[#38f9d7] text-black",
		titleClass: "text-[#43e97b]",
		failHint: "請再漱口一次～加油！",
	},
];

export const GAS_URL =
	"https://script.google.com/macros/s/AKfycbwcMXorYCJo32Q8FfLWGk7Jw221DX1PPaTorAlisE5ItJJfjtxm-okmD40Ke8Pg_u0N/exec";

export const VIDEO_LOCK_SECONDS = {
	1: 12,
	2: 11,
	3: 37,
	4: 14,
};
